/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package generatoare;

import java.awt.Dimension;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import static java.util.Locale.filter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Sofia Kub
 */
public class gen2 extends javax.swing.JFrame {

    private final Generatoare generator;
    private String key;
    private String textul;

    /**
     * Creates new form gen2
     */
    public gen2(Generatoare generatoare) {
        initComponents();
        this.generator = generatoare;
        setSize(1100, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(51, 51, 255));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Select the file to encrypt");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(60, 80, 230, 30);

        jButton1.setText("Open");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 130, 71, 29);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(360, 90, 246, 96);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(360, 400, 246, 96);

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(140, 280, 65, 29);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(51, 51, 255));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("          Generated key");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(60, 230, 230, 30);

        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(140, 440, 65, 29);

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(51, 51, 255));
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("        Encrypted text");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(60, 390, 230, 28);

        jLabel3.setBackground(new java.awt.Color(51, 51, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 980, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        JFileChooser jFileChooser1 = new JFileChooser(new File("C://"));

        if (jFileChooser1.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            Path path = jFileChooser1.getSelectedFile().toPath();

            String text = null;
            try {
                text = new String(Files.readAllBytes(path));
                jTextArea1.setText(text);

            } catch (IOException ex) {
                Logger.getLogger(gen2.class.getName()).log(Level.SEVERE, null, ex);
            }
            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            JTextArea jTextArea1 = new JTextArea();
            jTextArea1.setText(text);
            String[] words = text.split(" ");

            String cheie = new String();
            String textcriptat = new String();

            String c = "";
            for (String w : words) {
                System.out.println(w);

                try {
                    c = generator.getAlpha(w.length());
                    cheie = cheie.concat(c);
                    cheie = cheie.concat(" ");
                    c = generator.binar(c);
                    w = generator.binar(w);
                    textcriptat = textcriptat.concat(generator.XOR(c, w));
                    textcriptat = textcriptat.concat(" ");

                } catch (IOException ex) {
                    Logger.getLogger(gen2.class.getName()).log(Level.SEVERE, null, ex);
                }


    }//GEN-LAST:event_jButton1ActionPerformed
            key = cheie;
            textul = textcriptat;
        }

        jTextArea3.setText(textul);
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Text Files(*.txt)", "txt");
        JFileChooser f1 = new JFileChooser(new File("C://"));

        f1.setFileFilter(filter);
        f1.setCurrentDirectory(new File(System.getProperty("user.home")));
        f1.setDialogTitle("Save file");
        if (f1.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
            //Path path=f1.getSelectedFile().toPath();
            File file = f1.getSelectedFile();
            String text = key;
            try {
                BufferedWriter fw = new BufferedWriter(new FileWriter(file));
                fw.write(text);
                fw.close();
            } catch (IOException ex) {
                Logger.getLogger(gen2.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filter2 = new FileNameExtensionFilter("Text Files(*.txt)", "txt");
        JFileChooser f2 = new JFileChooser(new File("C://"));

        f2.setFileFilter(filter2);
        f2.setCurrentDirectory(new File(System.getProperty("user.home")));
        f2.setDialogTitle("Save file");
        if (f2.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
            //Path path=f1.getSelectedFile().toPath();
            File file = f2.getSelectedFile();
            String text2 = jTextArea3.getText();
            try {
                BufferedWriter fw2 = new BufferedWriter(new FileWriter(file));
                fw2.write(text2);
                fw2.close();
            } catch (IOException ex) {
                Logger.getLogger(gen2.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new gen2().setVisible(true);

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
